modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="projectz"
version="0.0.4"
displayName="ProjectZ"
authors="Swifty"
description="This is a open world zombie survival mod"
[[mods]]
modId="tac"
version="${file.jarVersion}"
displayName="Timeless and Classics Guns"
updateJSONURL=""
displayURL=""
authors="Timeless Development Team"
description='''
'''

[[dependencies.tac]]
modId="forge"
mandatory=true
versionRange="[32,)"
ordering="NONE"
side="BOTH"
[[dependencies.tac]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.tac]]
modId="framework"
mandatory=true
versionRange="[0.2.3,)"
ordering="NONE"
side="BOTH"




